name: flutter_fastapi_auth
description: A Flutter frontend for FastAPI authentication
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^5.8.0+1
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^0.13.4
  intl: ^0.20.2
  provider: ^6.0.0
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true


